ihm/urls.py
from django.conf.urls import url
from bacon import views

urlpatterns = [
    url(r'^$', views.home_page, name="home"),
    url(r'^probes/(?P<id>[0-9]+)$', views.view_probe, name="view_probe")
    ]

bacon/models.py
from django.db import models
from django.contrib.auth.models import User

class UserJambon(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  api_key = models.CharField(max_length=36)

class Probe(models.Model):
    id = models.AutoField(primary_key=True)
    ip_version = models.TextField(default='4')
    probe_type = models.TextField(default='icmp_echo')
    target = models.TextField(default='google.com')
    id_jambon = models.TextField(default="")

bacon/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from bacon.models import Probe

def home_page(request):

    if request.method == 'POST':
        ip_version = request.POST.get('ip_version', '')
        probe_type = request.POST.get('probe_type', '')
        target = request.POST.get('target', '')
        Probe.objects.create(ip_version=ip_version, probe_type=probe_type, target=target)
        return redirect('/')

    probes = Probe.objects.all()
    return render(request, 'home.html', {'probes':probes})

def view_probe(request, id):
    probe = get_object_or_404(Probe, pk=id)
    return render(request, 'probe.html', {'probe': probe})

bacon/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Jambon is the new chicken</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  </head>


  <body>
    <div class="container">


      {% block body %}{% endblock %}

    </div>
  </body>

bacon/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="text-center">
      <h1>Jambon is the new chicken</h1>
      <form method="POST" action='/'>
	<select id="id_ip_version_select" name="ip_version">
	  <option value="4">IPV4</option> 
	  <option value="6">IPV6</option>
	</select>
      
	<select id="id_probe_type_select" name="probe_type">
	  <option value="icmp_echo">icmp echo</option> 
	  <option value="icmp_request">ché pas moi icmp request?</option>
	</select>
      
	<label>Target host or IP address:
	  <input type="text" name="target" placeholder="Enter hostname or IP address" id="id_target">
	</label>
      
	<input type="submit" value="Submit" id="id_submit">
	{% csrf_token %}
      </form>
    </div>
  </div>
</div>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table id="id_list_table" class="table">
      <thead>
	<tr>
	  <th>ID</th>
	  <th>IP version</th>
	  <th>Probe type</th>
	  <th>Target</th>
	</tr>
      </thead>
      <tbody>
	{% for probe in probes %}
	<tr>
	  <td>{{ probe.id }}</td>
	  <td>{{ probe.ip_version }}</td>
	  <td>{{ probe.probe_type }}</td>
	  <td>{{ probe.target }}</td>
	</tr>
	{% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

bacon/templates/probe.html
{% extends 'base.html' %}

{% block body %}
    <h1>Probe {{ probe.id }}</h1>

  <table id="id_list_table">
    <thead>
      <tr>
	<th>ID</th>
	<th>IP version</th>
	<th>Probe type</th>
	<th>Target</th>
      </tr>
    </thead>
    <tbody>
      <tr>
	<td>{{ probe.id }}</td>
	<td>{{ probe.ip_version }}</td>
	<td>{{ probe.probe_type }}</td>
	<td>{{ probe.target }}</td>
      </tr>
    </tbody>
  </table>

{% endblock %}